<a href="https://colab.research.google.com/github/Taeseong-eom/TOM-Cafeteria-Model/blob/main/tam_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from joblib import load


data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/명진당식수/탐테스트.xlsx')
df = pd.DataFrame(data)

In [13]:
df

,요일,전주 식수,요일 평균 식수,시험기간,축제유무,간식배부,예비군유무,분류메뉴,주차,학관분류메뉴,...,개강주,종강주,시험끝목금,공휴일유무,학기번호,휴일 전날,휴일 다음날,연휴 전날,연휴 다음날,매움
0,목,524,462,0,0,0,0,밥류,11,육류,...,0,0,0,0,3,0,1,0,0,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   요일        1 non-null      object
 1   전주 식수     1 non-null      int64
 2   요일 평균 식수  1 non-null      int64
 3   시험기간      1 non-null      int64
 4   축제유무      1 non-null      int64
 5   간식배부      1 non-null      int64
 6   예비군유무     1 non-null      int64
 7   분류메뉴      1 non-null      object
 8   주차        1 non-null      int64
 9   학관분류메뉴    1 non-null      object
 10  방학유무      1 non-null      int64
 11  개강주       1 non-null      int64
 12  종강주       1 non-null      int64
 13  시험끝목금     1 non-null      int64
 14  공휴일유무     1 non-null      int64
 15  학기번호      1 non-null      int64
 16  휴일 전날     1 non-null      int64
 17  휴일 다음날    1 non-null      int64
 18  연휴 전날     1 non-null      int64
 19  연휴 다음날    1 non-null      int64
 20  매움        1 non-null      int64
dtypes: int64(18), object(3)
memory usage: 296.0+ bytes

In [15]:
import pandas as pd
import joblib

# 저장된 모델 불러오기
ridge_pipeline = joblib.load('/content/drive/MyDrive/Colab Notebooks/명진당식수/ridge_model_pipeline.joblib')

# 새로운 데이터 준비 (예: new_data)
# 새로운 데이터는 반드시 저장된 모델을 학습할 때 사용했던 컬럼과 동일한 컬럼을 가져야 합니다.


# 예측 수행
predictions = ridge_pipeline.predict(df)

print("새로운 데이터에 대한 예측 결과:", predictions)

새로운 데이터에 대한 예측 결과: [494.32058933]